module.exports = {
    errorCodes: [
        "Invalid",
        "OK",
        "Fail",
        "NoConnection",
        "InvalidPassword",
        "LoggedInElsewhere",
        "InvalidProtocolVer",
        "InvalidParam",
        "FileNotFound",
        "Busy",
        "InvalidState",
        "InvalidName",
        "InvalidEmail",
        "DuplicateName",
        "AccessDenied",
        "Timeout",
        "Banned",
        "AccountNotFound",
        "InvalidSteamID",
        "ServiceUnavailable",
        "NotLoggedOn",
        "Pending",
        "EncryptionFailure",
        "InsufficientPrivilege",
        "LimitExceeded",
        "Revoked",
        "Expired",
        "AlreadyRedeemed",
        "DuplicateRequest",
        "AlreadyOwned",
        "IPNotFound",
        "PersistFailed",
        "LockingFailed",
        "LogonSessionReplaced",
        "ConnectFailed",
        "HandshakeFailed",
        "IOFailure",
        "RemoteDisconnect",
        "ShoppingCartNotFound",
        "Blocked",
        "Ignored",
        "NoMatch",
        "AccountDisabled",
        "ServiceReadOnly",
        "AccountNotFeatured",
        "AdministratorOK",
        "ContentVersion",
        "TryAnotherCM",
        "PasswordRequiredToKickSession",
        "AlreadyLoggedInElsewhere",
        "Suspended",
        "Cancelled",
        "DataCorruption",
        "DiskFull",
        "RemoteCallFailed",
        "PasswordUnset",
        "ExternalAccountUnlinked",
        "PSNTicketInvalid",
        "ExternalAccountAlreadyLinked",
        "RemoteFileConflict",
        "IllegalPassword",
        "SameAsPreviousValue",
        "AccountLogonDenied",
        "CannotUseOldPassword",
        "InvalidLoginAuthCode",
        "AccountLogonDeniedNoMail",
        "HardwareNotCapableOfIPT",
        "IPTInitError",
        "ParentalControlRestricted",
        "FacebookQueryError",
        "ExpiredLoginAuthCode",
        "IPLoginRestrictionFailed",
        "AccountLockedDown",
        "AccountLogonDeniedVerifiedEmailRequired",
        "NoMatchingURL",
        "BadResponse",
        "RequirePasswordReEntry",
        "ValueOutOfRange",
        "UnexpectedError",
        "Disabled",
        "InvalidCEGSubmission",
        "RestrictedDevice",
        "RegionLocked",
        "RateLimitExceeded",
        "AccountLoginDeniedNeedTwoFactor",
        "ItemDeleted",
        "AccountLoginDeniedThrottle",
        "TwoFactorCodeMismatch",
        "TwoFactorActivationCodeMismatch",
        "AccountAssociatedToMultiplePlayers",
        "NotModified",
        "NoMobileDeviceAvailable",
        "TimeIsOutOfSync",
        "SMSCodeFailed",
        "AccountLimitExceeded",
        "AccountActivityLimitExceeded",
        "PhoneActivityLimitExceeded",
    ],
    currencyCode: [
        "Invalid",
	    "USD",
	    "GBP",
	    "EUR",
	    "CHF",
	    "RUB",
	    "PLN",
	    "BRL",
	    "JPY",
	    "NOK",
	    "IDR",
	    "MYR",
	    "PHP",
	    "SGD",
	    "THB",
	    "VND",
	    "KRW",
	    "TRY",
	    "UAH",
	    "MXN",
	    "CAD",
	    "AUD",
	    "NZD",
	    "CNY",
	    "INR",
	    "CLP",
	    "PEN",
	    "COP",
	    "ZAR",
	    "HKD",
	    "TWD",
	    "SAR",
	    "AED",
	    "ARS",
	    "ILS",
	    "BYN",
	    "KZT",
	    "KWD",
	    "QAR",
	    "CRC",
	    "UYU"
    ],
    currencyName: {
        "Invalid": 0,
	    "USD": 1,
	    "GBP": 2,
	    "EUR": 3,
	    "CHF": 4,
	    "RUB": 5,
	    "PLN": 6,
	    "BRL": 7,
	    "JPY": 8,
	    "NOK": 9,
	    "IDR": 10,
	    "MYR": 11,
	    "PHP": 12,
	    "SGD": 13,
	    "THB": 14,
	    "VND": 15,
	    "KRW": 16,
	    "TRY": 17,
	    "UAH": 18,
	    "MXN": 19,
	    "CAD": 20,
	    "AUD": 21,
	    "NZD": 22,
	    "CNY": 23,
	    "INR": 24,
	    "CLP": 25,
	    "PEN": 26,
	    "COP": 27,
	    "ZAR": 28,
	    "HKD": 29,
	    "TWD": 30,
	    "SAR": 31,
	    "AED": 32,
	    "ARS": 34,
	    "ILS": 35,
	    "BYN": 36,
	    "KZT": 37,
	    "KWD": 38,
	    "QAR": 39,
	    "CRC": 40,
	    "UYU": 41
    }
};